language: julia

julia:
  - 1.0
  - 1.2
  - nightly

os:
  - linux
  - osx
  - windows

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder());'
